[package]
name = "web"
version = "0.1.0"
authors = ["Boris-Chengbiao Zhou <bobo1239@web.de>"]
edition = "2021"

[dependencies]
shared = { path = "../shared" }
rocket = { version = "0.5.0", default-features = false }
itertools = "0.14.0"
tokio = { version = "1.2.0", features = ["full"] }
